site_name: NSI - Clément Braun
theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.instant
    - navigation.tracking
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple
      accent: orange
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple
      accent: orange
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - attr_list




extra_css:
  - stylesheets/extra.css
  - stylesheets/glassmorphism.css
  - stylesheets/modern-design.css
  - stylesheets/animations.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/modern-interactions.js

site_url: https://clementbraunnsi.github.io/nsi-courses/

# Mode développement plus rapide
watch:
  - docs
  - mkdocs.yml

# Désactiver la validation stricte en dev
strict: false

# Optimiser le cache
use_directory_urls: true

copyright: |
  &copy; 2025 <a>Clément Braun</a>

