site_name: NSI - Clément Braun
theme:
  name : material
  logo : images/test.png
  features :
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  language: fr
  palette:
    primary: indigo
    accent: blue
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - attr_list




extra_css:
  - stylesheets/extra.css
  - dostylesheets/glassmorphism.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.js

site_url: https://clementbraunnsi.github.io/nsi-courses/
use_directory_urls: true

copyright: |
  &copy; 2025 <a>Clément Braun</a>

